packages:
  - 'internal/*'
  - 'internal/lint-configs/*'
  - 'packages/*'
  - 'packages/@core/*'
  - 'packages/effects/*'
  - 'apps/*'
  - 'scripts/*'

catalog:
  # Vue 核心
  vue: ^3.5.13
  vue-router: ^4.5.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  '@vueuse/core': ^14.2.1
  '@vueuse/components': ^14.2.1

  # 构建工具
  vite: ^7.3.2
  typescript: 5.9.3
  vue-tsc: ^3.2.7
  turbo: ^2.5.0
  unbuild: ^3.5.0
  tsdown: ^0.12.0

  # Vite 插件
  '@vitejs/plugin-vue': ^6.0.6
  '@vitejs/plugin-vue-jsx': ^5.1.5
  'unplugin-auto-import': ^20.2.0
  'unplugin-vue-components': ^30.0.0
  'unplugin-vue-router': ^0.16.1
  'vite-plugin-svg-icons': ^2.0.1
  'vite-plugin-mock': ^3.0.2
  'vite-plugin-compression': ^0.5.1
  'rollup-plugin-visualizer': ^6.0.5

  # UnoCSS
  unocss: 66.6.8
  '@unocss/preset-uno': 66.6.8
  '@unocss/preset-attributify': 66.6.8
  '@unocss/preset-icons': 66.6.8

  # HTTP / 工具
  axios: ^1.15.2
  dayjs: ^1.11.19
  qs: ^6.14.0
  mitt: ^3.0.1
  less: ^4.4.2

  # UI 库
  'ant-design-vue': ^4.2.6
  '@ant-design/icons-vue': ^7.0.1
  'element-plus': ^2.13.7
  '@element-plus/icons-vue': ^2.3.2
  'naive-ui': ^2.44.1
  '@arco-design/web-vue': ^2.57.0
  'tdesign-vue-next': ^1.19.1

  # 工程工具
  cross-env: ^7.0.3
  rimraf: ^6.0.1
  cz-git: ^1.12.0
  czg: ^1.12.0
  lefthook: ^1.11.0
  only-allow: ^1.2.1
  lint-staged: ^16.2.6

  # Lint
  eslint: ^9.39.1
  prettier: ^3.6.2
  stylelint: ^16.25.0
  oxlint: ^1.6.0
  oxfmt: ^0.47.0
  cac: ^7.0.0
  execa: ^9.5.2
  consola: ^3.4.2
  '@clack/prompts': ^0.10.1
  '@vue/eslint-config-typescript': ^14.6.0
  '@vue/eslint-config-prettier': ^10.2.0
  'eslint-plugin-vue': ^10.5.1
  'eslint-plugin-simple-import-sort': ^12.1.1
  'globals': ^16.5.0

  # Stylelint
  'stylelint-config-standard': ^39.0.0
  'stylelint-order': ^7.0.0
  'postcss-html': ^1.8.0
  'postcss-less': ^6.0.0

  # Commitlint
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1

  # NProgress
  nprogress: ^0.2.0
  '@types/nprogress': ^0.2.3

  # TDesign auto-import
  '@tdesign-vue-next/auto-import-resolver': ^0.1.6

  # Types
  '@types/node': ^22.19.17
  '@types/qs': ^6.14.0
