import { defineConfig } from 'tsdown';

export default defineConfig({
  clean: true,
  dts: true,
  entry: ['src/index.ts'],
  format: ['esm'],
  external: [
    'vite',
    '@vitejs/plugin-vue',
    '@vitejs/plugin-vue-jsx',
    'unocss',
    'unocss/vite',
    'unplugin-auto-import',
    'unplugin-vue-components',
    'unplugin-vue-router',
    'unplugin-vue-components/vite',
    'unplugin-auto-import/vite',
    'unplugin-vue-router/vite',
    'rollup-plugin-visualizer',
    'vite-plugin-compression',
    'vite-plugin-dts',
    'vite-plugin-html',
    'vite-plugin-pwa',
    'vite-plugin-vue-devtools',
    'dotenv',
    'dayjs',
    'sass',
    'archiver',
    'cheerio',
    'html-minifier-terser',
    'nitropack',
    '@jspm/generator',
    'resolve.exports',
    '@fast-vue3/node-utils',
    '@pnpm/workspace.read-manifest',
  ],
});
