import { useResponseSuccess } from '~/utils/response';

const menus = [
  {
    id: 1,
    parentId: 0,
    name: '首页',
    path: '/home',
    icon: 'HomeOutlined',
    sort: 1,
    status: 'active',
    type: 'menu',
  },
  {
    id: 2,
    parentId: 0,
    name: '仪表盘',
    path: '/dashboard',
    icon: 'DashboardOutlined',
    sort: 2,
    status: 'active',
    type: 'menu',
  },
  {
    id: 3,
    parentId: 0,
    name: '系统管理',
    path: '/system',
    icon: 'SettingOutlined',
    sort: 3,
    status: 'active',
    type: 'directory',
  },
  {
    id: 4,
    parentId: 3,
    name: '用户管理',
    path: '/system/user',
    icon: 'UserOutlined',
    sort: 1,
    status: 'active',
    type: 'menu',
  },
  {
    id: 5,
    parentId: 3,
    name: '角色管理',
    path: '/system/role',
    icon: 'LockOutlined',
    sort: 2,
    status: 'active',
    type: 'menu',
  },
  {
    id: 6,
    parentId: 3,
    name: '菜单管理',
    path: '/system/menu',
    icon: 'MenuOutlined',
    sort: 3,
    status: 'active',
    type: 'menu',
  },
  {
    id: 7,
    parentId: 0,
    name: '日志中心',
    path: '/log',
    icon: 'FileTextOutlined',
    sort: 4,
    status: 'active',
    type: 'directory',
  },
  {
    id: 8,
    parentId: 7,
    name: '登录日志',
    path: '/log/login',
    icon: '',
    sort: 1,
    status: 'active',
    type: 'menu',
  },
  {
    id: 9,
    parentId: 7,
    name: '操作日志',
    path: '/log/operation',
    icon: '',
    sort: 2,
    status: 'active',
    type: 'menu',
  },
  {
    id: 10,
    parentId: 7,
    name: '错误日志',
    path: '/log/error',
    icon: '',
    sort: 3,
    status: 'active',
    type: 'menu',
  },
  {
    id: 11,
    parentId: 0,
    name: '系统设置',
    path: '/settings',
    icon: 'ToolOutlined',
    sort: 5,
    status: 'active',
    type: 'menu',
  },
  {
    id: 12,
    parentId: 0,
    name: '数据分析',
    path: '/analytics',
    icon: 'BarChartOutlined',
    sort: 6,
    status: 'active',
    type: 'menu',
  },
  {
    id: 13,
    parentId: 3,
    name: '用户新增',
    path: '',
    icon: '',
    sort: 0,
    status: 'active',
    type: 'button',
    permission: 'user:create',
  },
  {
    id: 14,
    parentId: 3,
    name: '用户编辑',
    path: '',
    icon: '',
    sort: 0,
    status: 'active',
    type: 'button',
    permission: 'user:edit',
  },
  {
    id: 15,
    parentId: 3,
    name: '用户删除',
    path: '',
    icon: '',
    sort: 0,
    status: 'active',
    type: 'button',
    permission: 'user:delete',
  },
];

export default defineEventHandler(() => {
  return useResponseSuccess(menus);
});
